# Generated by Django 4.2.5 on 2023-09-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_message_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
