# Generated by Django 4.2.5 on 2023-09-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_chatmessage_remove_message_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
